version: '2'
services:
    
  #MariaDB Server
  melissa-dbserver:
    restart: always
    image: mariadb:10.2
    networks:
      - melissa_network
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - melissa-db:/var/lib/mysql
    env_file:
      - .env
      
  melissa-service:
    restart: always
    image: ntidev/melissa-service:dev
    ports: 
      - 8095:8095
    networks:
      - melissa_network
#      - default
    volumes:
        - ./etc:/app/etc
    env_file:
      - .env
    depends_on:
      - melissa-dbserver
     
networks:
  melissa_network:
#  default:
#    external:
#      name: other_network
    
volumes:
  melissa-db:
